### ISSUE TITLE
Voting for next MVP

### ISSUE THREAD

**Issue by phuoc-thanh** [dtr-group/internal-research#1]
Minimum Viable Product, will be written on:

1. C++: Same as bitcoin

2. Java: Same as hyperledger

3. Python/Go: Another choice

4. Other lang - submit a reason

Please submit your answer below

**Comment by phuoc-thanh** [comment]
I prefer Java. C++ is also be OK

**Comment by nguyenhuulocla2006** [comment]
I prefer Java

**Comment by mrdaovn** [comment]
newbie for any.
Prefer Nodejs

**Comment by SteveNguyen1190** [comment]
I prefer Python

**Comment by HongQuanIT** [comment]
C++ or Nodejs
